services:
  - type: web
    name: mimo-front
    branch: main             # branche à déployer
    buildCommand: npm install && npm run build
    startCommand: npm run start   # pas utilisé pour static env
    staticPublishPath: build
    plan: free  
