services:
  - type: static               # <-- MUST be static
    name: my-react-app
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: build   # dossier généré par CRA
    plan: free  
